geno_last_joined<-read.csv(file="../geno_hema_joined.uniq.last.within3years.csv")
m<-lm(anemia_who~rs679515_dosage*log(gpath+1)+msex+educ+age,data=geno_last_joined)
capture.output(summary(m),file="log(gpath).output.txt",append = F)
m<-lm(hemacrit~rs679515_dosage*log(gpath+1)+msex+educ+age,data=geno_last_joined)
capture.output(summary(m),file="log(gpath).output.txt",append = T)
m<-lm(hemoglbn~rs679515_dosage*log(gpath+1)+msex+educ+age,data=geno_last_joined)
capture.output(summary(m),file="log(gpath).output.txt",append = T)
m<-lm(log_hil1b~rs679515_dosage*log(gpath+1)+msex+educ+age,data=geno_last_joined)
capture.output(summary(m),file="log(gpath).output.txt",append = T)
m<-lm(rbc~rs679515_dosage*log(gpath+1)+msex+educ+age,data=geno_last_joined)
capture.output(summary(m),file="log(gpath).output.txt",append = T)
